### ISSUE TITLE
specific error message for commas between contracts/metadata

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel#1022]
**Is your feature request related to a problem? Please describe.**

Writing this feels natural:
```
variable | doc "this is a variable" | contract1 | optional
```

But on multiple lines, it's tempting to add commas between pipes lines, like in most of the nickel code:

```
variable
 | doc "this is a variable",
 | contract1,
 | optional
```

Which gives the message:

```
error: unexpected token
  ┌─ /home/solene/dev/nickel/lib.ncl:9:5
  │
9 │     | contract1,
  │     ^
```

**Describe the solution you'd like**

If possible, the parser could tell that there is an extra comma at the wrong place

**Comment by matthew-healy** [comment]
Thanks for raising this! I agree that's not the most helpful error message. 

I think this would be best resolved with a specific "invalid metadata annotation" error which is raised whenever a metadata annotation is encountered in a place we don't expect it. That could be after a `,`, but it could also be raised when attempting to apply e.g. `| optional` in a let binding. Currently the valid positions of metadata annotations are entirely enforced within the parser, so when using them in invalid ways you get "raw" `unexpected token` errors since there's no production to handle the input source.

**Comment by yannham** [comment]
This is unfortunately quite hard given the current parser infrastructure. LALR parsers don't give a whole lot of context nor flexibility around unexpected token errors. It might be doable at the cost of introducing a phony rule to match a metadata where a field definition is expected, and produce a custom error, but it sounds quite ad-hoc (I imagine there are a lot of other places where we could have better, customized error messages about what is expected and why). But if we do that for too many things, I fear the grammar becomes a mess.

A saner approach is to change the parsing approach (like writing a recursive descent parser), but it has other obvious disadvantages and isn't a small change.

> But on multiple lines, it's tempting to add commas between pipes lines, like in most of the nickel code:

It's an interesting intuition, because usually most modern programming languages are newlines-insensitive, so I wouldn't expect that to work. That being said, I have written commas at this location while in "automatic mode" too.

**Comment by yannham** [comment]
I think we can revisit parsing error message if/when we change the parser infrastructure (once the syntax is stabilized, it can make sense to use something else than LALRPOP), but for now we won't explore this path further, so I'm closing.
