### ISSUE TITLE
Bikeshed syntax for function body separator

### ISSUE THREAD

**Issue by asymmetric** [tweag/nickel#1157]
**Is your feature request related to a problem? Please describe.**

The current syntax for Nickel distinguishes between `->`, used in type signatures, and `=>`, used to separate the arguments and the body of a function:

```nickel
let add : Num -> Num -> Num = fun a b => a + b in add 3 5
```

The similarity between the two symbols can be a source of confusion for novice users

Moreover, when the type is omitted, it can simply be hard to remember which arrow one should use:

```
let add = fun a b => a + b in add 3 5
```

Considering types can be inferred, there is also the option

**Describe the solution you'd like**

There are several options:

1. use `->` everywhere, like one does in OCaml for anonymous functions:

```
let add : Num -> Num -> Num = fun a b -> a + b in
let add' = fun a b -> a + b in add' 3 5
```

2. use another separator for the function body that looks less like `->`

**Describe alternatives you've considered**

One could consider larger syntax changes, like moving the arguments to the left-hand side of the assignment, again like in OCaml:

```
let add a b : Num -> Num -> Num = a + b in
let add' a b = a + b in add' 3 5
```

This would obviate the need for a body separator, and would drop the `fun` keyword, which could be seen as both an advantage (smaller syntax footprint) and a disadvantage (harder to spot functions when skimming through code)

**Comment by matthew-healy** [comment]
Before getting into bikeshedding this, I'd be interested to hear the justification behind stating:

> The similarity between the two symbols can be a source of confusion for novice users

I may be biased as I personally didn't find this to be a problem when onboarding to Nickel, but I've also not heard others complain about this particular piece of syntax before.

While I'm sure it's true that the difference between `->` and `=>` may not be immediately obvious, I also think that understanding the syntax of a new language is _always_ going to incur some overhead. It's not clear to me that this is an issue with the language syntax itself. I wonder whether this is something that could be resolved with, for example, improved tutorial content rather than requiring a syntactic change.

**Comment by yannham** [comment]
For the record, there has been some prior discussion on function syntax (including having an OCaml-like variant) in #207, on then in #569.

**Comment by asymmetric** [comment]
@matthew-healy sure that's fair, and that statement is completely based on my personal experience :)

I had a hard time remembering which to use, but it's quite likely that I'd internalize this pretty fast (I even came up with the mnemonic that `=>` is `-> + =`, which matches the order in which they're used :smile: ).

@yannham thanks for linking those issues. Seems like the ML syntax came up both times, and was most recently closed as something to look into later -- which I suppose is now, since 1.0 is the next release?

**Comment by yannham** [comment]
> @yannham thanks for linking those issues. Seems like the ML syntax came up both times, and was most recently closed as something to look into later -- which I suppose is now, since 1.0 is the next release?

It's not necessarily now, as it is a non-breaking change in principle (if just adding a new function syntax, while keeping the `fun =>` part). Same as let-blocks (#494). The idea was to wait until enough people complain that they missed such a thing :stuck_out_tongue:

On the other hand, the basic function syntax is a breaking change, so we better settle that before 1.0.

**Comment by yannham** [comment]
Ah, I think we might have a misunderstanding here: when I talk about the ML syntax, I mean the `let foo arg1 arg2 arg3 = body`, which would indeed be a backward-compatible addition. But maybe you meant using a `->` everywhere, by saying ML syntax, as the original motivation of this issue? In which case, it hasn't been discussed before indeed, and is a breaking change, so this is issue is still quite relevant!

I don't have a strong opinion either. Only one symbol is maybe less confusion; on the other hand, one could also argue that `=>` and `->` can be a nice distinction between a term-related syntax and a type-related syntax, especially because since RFC002, both syntax are merged. Let's wait for more opinions on this :slightly_smiling_face:

**Comment by yannham** [comment]
The original request is fair and could be a reasonable syntax. However, the current syntax seems to also be reasonable with an easy rationale (`->` is for types, `=>` is for expressions [match, functions, etc.]), and we didn't find the motivation strong enough to change the syntax at this point. Thanks again @asymmetric nonetheless for taking the time to write the issue and let a public bikeshedding happen :slightly_smiling_face:
