### ISSUE TITLE
Make pre-releases for 1.0

### ISSUE THREAD

**Issue by piegamesde** [tweag/nickel#1280]
Given that the release notes track 1.0 as the next version, and also contain quite a few big breaking changes, I'd like to propose doing some in-between releases first. For example, there could be a 0.4.0 version, and then going to 1.0-beta or 1.0-pre before doing the actual release.

**Comment by yannham** [comment]
I wonder what could be the content of the 0.4.0 version? If it's just a 1.0 but with a less scary name, I'm tempted to say  it sounds a bit artificial.

I anticipate that actually releasing a past version (say, stopping 1 month ago) would be difficult as a lot of changes have been made by pieces but with eventual consistency for 1.0 in mind (typically, if you arbitrarily cut somewhere, you might end up with long name for primitive types, but short ones for stdlib module, etc.). Also people will have to adapt to breaking changes two times in a row: doing one painful pass might be less painful, in the end.

Doing an `1.0-beta` or `1.0-pre` is totally possible, although it's mostly a naming game and wouldn't change the content of the release much.

**Comment by piegamesde** [comment]
SemVer is not arbitrary. If you release 1.0 and one of those changes turns out to be a mistake or requiring improvements, you might end up having to go to 2.0 in order to fix it if the fix is not backwards compatible. (And since that's a high bar, you'd more likely simple remain stuck with the mistake because the cost of fixing it would be too high.) But if you release the changes as 0.4 first and an issue comes up, no problem: Simply fix it in 0.5 and delay the 1.0 release a bit.

The broader point is, you want to keep the changes in a release from 0.x to 1.0 minimal. As an example, when Rust introduces a new feature, they keep it on nightly for a while and once things have settled down they mark it as stable. They wouldn't change major parts of the design in a stabilization PR. Because that's something you do *before* declaring it as stable.

**Comment by yannham** [comment]
While I agree in part, I think there is a kind of psychological factor that is also not always totally rational with respect to releasing `1.0` or `2.0` or whatever. For a user updating to latest Nickel, they still have to do the same job for updating from `0.4` to `0.5` than from `1.0` to `2.0` if we make non backward compatible changes, whatever numbers we choose. You'll find a good chunk of projects in the wild, which have existed for many years, are widely used, stable and used in production, but are still at `0.X.Y`, which honestly doesn't make a lot of sense to me (it doesn't buy much to users who already depend on the current version of such a tool to always say "beware we might break everything tomorrow!"; if you want to do so, why not update the major version).

Agreed, releasing a 1.0 is a statement saying we're reasonably confident that we won't break stuff horribly in the future. So maybe people would migrate their code more easily from `0.3` to `1.0` than from `0.3` to `0.4`. Or maybe not, I honestly don't know.

Another Nickel-specific consideration is that we have a bit of a chicken-and-egg problem with adoption (I'm not saying this is the only factor, but it does have an impact). People are reluctant to try the new shiny tool if it's saying explicitly that it could break everything and wreck havoc in-between two versions, so they wait for more stability. But as language developers, we are at a point where we need more feedback and battle-testing before proceeding further, otherwise we're at risk of developing blindly and solving hallucinated problems that may actually not exist in practice.

Releasing a 1.0 is a way of saying that you should be able to use Nickel in a more serious way. Keep in mind that a lot of breaking changes are also syntactic or concern the stdlib API, going from a state "this was used in the prototype without giving a second thought about it because it wasn't the problem then" to "we've actually put a bit of thought in this", and public bikeshedding issues. There is a limited risk of reverting those changes again.

That being said, I recognize there is also a fair amount of non-trivial semantics changes, and you never know what design mistake you made, especially for non-standard designs like a configuration language. I personally think a `1.0-pre` or `beta` or `alpha` is fine, doesn't cost much but still give us a bit more slack. I'm more mitigated about `0.4` because of the adoption issue mentioned above. But this issue is good to gather people's opinion.

Maybe @aspiwack (but he's on vacation right now, so this is a delayed invocation) or @mboes have more thoughts on this matter.

**Comment by aspiwack** [comment]
I hadn't seen this thread, sorry. I'm not in favour of doing a 0.4. We have decided that our next version is going to be what we label 1.0, let's stick to it. I'm fine with releasing a 1.0 beta ahead of time. But honestly, considering the size of our user-base, I doubt that we'll get much feedback.
