### ISSUE TITLE
`&&` can't be partially applied

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1281]
**Describe the bug**
If one tries to partially apply the curried version of boolean operators such as `(&&)` or `(||)`, we get an error. This doesn't happen with other operators (e.g `(==)` or `<`).

**To Reproduce**

```
nickel> (&&)
<func>

nickel> (&&) true
error: not enough arguments
  ┌─ repl-input-6:1:2
  │
1 │ (&&) true
  │  ^^ && expects 2 arguments, but not enough were provided

nickel> (&&) true false
false
```

**Expected behavior**
`(&&) true` should be a function of one argument returning `fun rhs => true && rhs`, and should evaluate without errors.

**Additional context**
This might be related to the lazyness of boolean operators, which makes them `op1` under the hood, while they're morally `op2`. I suspect the primop application isn't properly saturated.

**Comment by vkleen** [comment]
Your suspicion looks correct to me. The code in `src/eval/operation.rs` for evaluating, say, `BoolAnd` is called as soon as the first argument is done evaluating (because it's technically a unary operator). But that code immediately checks that a second argument is already on the stack. We could probably fix that by always returning a closure that's waiting for the second argument.
