### ISSUE TITLE
Parsing of negative numbers is non-intuitive

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#1308]
**Describe the bug**
Parsing of negative numbers doesn't work as expected.

**To Reproduce**

The following program:

```ncl
%elem_at% [1, 2, 3] -1
```

raises an unexpected token error:

```
error: unexpected token
  ┌─ repl-input-0:1:21
  │
1 │ %elem_at% [1, 2, 3] -1
  │     
```

This can be fixed by wrapping `-1` in parenthesis, but it doesn't feel like this should be necessary.

Another example:

```ncl
let f = fun arr idx => %elem_at% arr idx in
f [1, 2, 3] -1
```

raises a dynamic type error:

```
error: dynamic type error
  ┌─ repl-input-2:1:1
  │
1 │ f [1, 2, 3] -1
  │ ^^^^^^^^^^^^^^ this expression has type Function, but Number was expected
  │
  ┌─ repl-input-1:1:12
  │
1 │ let f = fun arr idx => %elem_at% x y
  │         --------------------------- evaluated to this
  │
  = (-) expects its 1st argument to be a Number

```

seemingly because it parses the above as `(f [1, 2, 3]) - (1)`.

**Expected behavior**

Both of the above examples should parse `-1` as the numeric value `-1`. I'm not sure if this is a regression, as it's not something I've run into previously, and it seems like a pretty noticeable issue.

**Comment by matthew-healy** [comment]
Probably worth noting that I discovered this while rewriting [this test](https://github.com/tweag/nickel/blob/master/tests/integration/stdlib_arrays_fail.rs#L13) which already parenthesises the negative number, so I guess this was known about at some point.

**Comment by matthew-healy** [comment]
After discussing this with @vkleen on Slack, this isn't _really_ a bug. It's possible we could tweak the parser to make it so `f x -1` parses as a number but `f x - 1` parses as subtraction, but that would be a backwards incompatible change so we can't really consider it until a theoretical Nickel 2.0. 

In the meantime, the error messages should definitely be improved.

**Comment by yannham** [comment]
This issue is mostly unavoidable, if you have both:

- space are not significant in arithmetic expressions (they can be removed)
- a unary negation operator and a binary subtraction operator with the same symbol

You can check for example that this is exactly the same in OCaml and Haskell currently, with the same error message (type error in OCaml or function applied to too few arguments in Haskell). I'm don't think this would be a good idea to make a special case (what would be the condition), which is also hard to treat in a lexer + parser approach. I much prefer users to add additional parentheses, which is a minor cost.

Maybe we can issue better error messages, I haven't thought too hard about this. But it doesn't seem totally obvious: it looks like it would involve some form of heuristics, at parsing time probably. But the error happen later. Maybe it could be a warning?

**Comment by matthew-healy** [comment]
> (what would be the conditions, by the way?)

At least in my head, I'd like `f x -1` to parse as `f x (-1)` and `f x - 1` to parse as `(f x) - 1`. This feels really intuitive, and as far as I can tell the only cost is that you can no longer use infix binary operators without putting spaces around them, which I think is something most people tend to do anyway.

This is actually exactly how I've implemented negation [in my own toy language](https://github.com/matthew-healy/untitled-programming-language-project/blob/trunk/src/parser.lalrpop#L117).

> Maybe we can issue better error messages,

I think we should be able to improve the error messages. If we get a dynamic type error arising as a result of the first argument to subtraction being a function we can just add a note to the error message to say "Hey, it looks like you might be trying to pass a negative number as a function argument, try wrapping it in parentheses instead." No need for it to be a new error or anything - it just needs to point beginners in the right direction until they learn this particular quirk of the language.

The error when passing a negative number to a primop is significantly worse, but it's also far less likely that most users would ever run into that, so I don't think fixing it is a priority.

**Comment by yannham** [comment]
> At least in my head, I'd like f x -1 to parse as f x (-1) and f x - 1 to parse as (f x) - 1. This feels really intuitive, and as far as I can tell the only cost is that you can no longer use infix binary operators without putting spaces around them, which I think is something most people tend to do anyway.

I don't think that this is entirely true. In fact I don't put spaces around operators that have priorities for example: `2*a + 4*b`. Granted, it's probably more rare with subtraction, but honestly I don't know what other people do or don't. At the very least I think this assertion needs to be supported by facts (could be measured in other programming languages).

> I guess I'd be interested to know why you think
>
>>    spaces are not significant in arithmetic expressions (they can be removed)
>
> is an important feature to maintain?

First, I lied :stuck_out_tongue: because we accept dash inside identifiers, `a-2` is an identifier while `a - 2` is an arithmetic expression. So it's not entirely true. But, we did that for a precise reason (dash are common in configuration and we don't want to have to escape all the field containing dashes with double quotes) and understood the trade-off.

One argument could be for the formatter, because the more space-insensitive is the grammar, the more freedom to re-flow the source code. But honestly it's not the reason.

All in all, while I can see why you think `f 1 -2` should be parsed as `f 1 (-2)`, and I probably tend to agree, I don't find the argument to be super strong either, but mostly a matter of taste. I don't think saying people should put spaces around subtraction is very different from saying people should put parentheses around negative numbers used in an application.

 As such, because it would be a breaking change, the motivation is a bit insufficient at the moment IMHO.

> I think we should be able to improve the error messages. If we get a dynamic type error arising as a result of the first argument to subtraction being a function we can just add a note to the error message to say "Hey, it looks like you might be trying to pass a negative number as a function argument, try wrapping it in parentheses instead." No need for it to be a new error or anything - it just needs to point beginners in the right direction until they learn this particular quirk of the language.

Sure, we can do something like that. But it would be hard to differentiate from a missing argument, e.g.

```nickel
let f_3_args = fun x y z => x*y*z in
(f_3_args 0 1) - 2
```

Here, it's an actual subtraction, but `f_3_args` is missing an argument. I don't imply that we shouldn't do it because of that, but just to keep in mind that we have to find the right balance between giving helpful hints and being misleading :slightly_smiling_face:

**Comment by matthew-healy** [comment]
> At the very least I think this assertion needs to be supported by facts (could be measured in other programming languages).

This is very reasonable! I was mostly just hypothesizing. My assumption would be that the languages that do/don't support this are roughly correlated with languages that do/don't require parentheses around function arguments, but we could definitely look into this a bit more if we ever think about changing it.

> As such, because it would be a breaking change, the motivation is a bit insufficient at the moment IMHO. 

Yep, that's really fair. I opened the issue because I was surprised by the behaviour but most of the languages I write with any regularity are "C-family", and I'm sure this is less surprising to anyone with more of a functional background. :grin: 

I'll try to take a look at the options for improving the error messages when I have some time. I agree that it won't be totally trivial, but I think the impact is worth it to help out anyone like me who hasn't experienced this sort of thing before. :sweat_smile:

**Comment by yannham** [comment]
I don't think anyone currently has the drive and the motivation to push the "look for better error messages" further, and the original question is answered as: we won't change the current syntax, for all the reasons given in this thread.
