### ISSUE TITLE
Normalizing contracts applied to record fields are called too late

### ISSUE THREAD

**Issue by thufschmitt** [tweag/nickel#1415]
**Describe the bug**

(maybe that's not a bug, and it's just me abusing the contract system. But opening any way).

If a record has a contract attached to one of his fields (say `{ foo | Contract = 1234 }`), then (it looks like) `Contract` will only be applied when accessing the `foo` field, _after_ all the merges have been done. Contrary to `{ foo = 1234 | Contract }` for which `Contract` will be applied _before_ potential merges.
This is meaningful if `Contract` does some normalization of its argument.

**To Reproduce**

Example taken from https://github.com/nickel-lang/nickel-nix/tree/packages-as-list:

```nickel
let RecordAsArray
  | doc m%"
    A record, but that can be expressed as an `Array { name : String, .. }`, such that
    `[ { name = "name_1", ..t1 }, ..., { name = "name_n", ..tn } ]` gets normalized to
    `{ name_1 = { name = "name_1", ..t1 }, ..., name_n = { name = "name_n", ..tn } }`
  "%
  = fun FieldContract =>
    let normalize = fun array => std.array.fold_left (fun acc elt => acc & { "%{elt.name}" = elt }) {} array
    in
    fun lbl value =>
      if std.is_array value then
        value
        |> normalize
      else
        value
  in
{
  foo | RecordAsArray Dyn = [{ name = "x" }],
  # foo = [{ name = "x" }] | RecordAsArray Dyn,
  foo = { y = 1 }
}
```

This will fail with an error saying (roughly): “Can't merge the list `[{name = "x" }]` with the record `{ y = 1 }`”.
Otoh, commenting the first field of the record and uncommenting the second will do the expected (by me at least) thing, and evaluate to `{ x.name = "x", y = 1 }`.

**Expected behavior**

The first case should just work and evaluate to the same thing as the second one

**Environment**
 - OS name + version: NixOS 23.05
 - Version of the code: 89a1382cfd6dc1a72dca491e93980f514305cb18 and 36425a45a838ec16b7df169c3d141c2e2a9f0d24 (latest master)

**Additional context**

Found out while trying to solve https://github.com/nickel-lang/nickel-nix/issues/55

**Comment by vkleen** [comment]
I'm pretty sure this happens because the parser desugars multiple occurrences of the same record field into merges. That is, your example will be transformed into

```nickel
{
  foo | RecordAsArray Dyn = [{ name = "x" }] & { y = 1 }
}
```

syntactically, before the evaluator ever sees it. I'm not sure there's a great way of solving this. For example, making the parser immediately aware of contract annotations on fields by transforming

```nickel
{
  foo | Contract = a,
  foo = b
}
```

into `{ foo | Contract = (a | Contract) & b }` won't help if `b` would need to be normalised for the merge to make sense.

Note that using `{ foo = [{ name = "x" }] | RecordAsArray Dyn }` will not result in the `RecordAsArray` contract being attached to the field `foo`. Instead it will be one-time contract check and normalisation.

**Comment by yannham** [comment]
As Viktor says, piecewise fields definition desugars to merging. Given the resulting desugared expression, the current semantics is intentional, and was in fact different pre-1.0.0: we would cross-apply contracts eagerly upon merging. This came with a lot of issues (that, funnily, we uncovered together @thufschmitt while working on early Nixel), one common example being a bunch of spurious missing fields errors when you're building a value by successive mergings whereas incomplete value doesn't respect the final contract, yet.

With your proposed semantics, `{my_field | {need_foo, need_bar}} & {my_field.need_foo = 1} & {my_field.need_bar = false}` would fail with "missing field `need_bar`" on the first part of the merge. See the RFC005 for more examples.

If I may ask, what is the motivation behind using a piecewise field definition like this? It's using merging because it's a clear and simple semantics, but honestly the original design was rather to accomodate field per field definition such as `foo.bar = 1, ..., foo.baz = 2, ..., foo.baz.blorg = 3`, which would desugar to `foo = {bar = 1}, foo = {baz = 2}, foo = {baz = {bloarg = 3}, ...` and then to merging. However relying on piecewise definitions to implement non-trivial merging behavior is honestly more surprising to me.

Maybe what you want would be better expressed with custom merge functions, them are supposed to basically overload `&` and thus execute before the merging take place. Unfortunately, they're not there yet. 

Another solution would be to change the desugaring of

```
{
  foo | Contract = a,
  foo = b
}
```

from

```
{
  foo | Contract = a & b
}
```

to

```
{
  foo | Contract = a & (b | Contract)
}
```

But this feels ad-hoc and is arguably less "natural" than the current semantics, IMHO.

**Comment by thufschmitt** [comment]
> transforming ... into { foo | Contract = (a | Contract) & b } won't help if b would need to be normalised for the merge to make sense.

Damn! I was hoping for something like that to be possible, but it indeed doesn't make much sense.

> This came with a lot of issues (that, funnily, we uncovered together @thufschmitt while working on early Nixel)

Ahah, I should have expected this was related :smile: 

> If I may ask, what is the motivation behind using a piecewise field definition like this?

Actually piecewise definition was just a compact way of showing it, the original code was using merging. Something along the lines of 

```nickel
...
# Actually defined in a library file
let bashShell = {
    packages | RecordAsArray Derivation = [ pkgs.bash ],
  }
in
# In the main file
bashShell & {
  packages = [ pkgs.hello ],
```

> Maybe what you want would be better expressed with custom merge functions

Yes, this is just a poor man's merge function

**Comment by thufschmitt** [comment]
I'll close this since there isn't much to be done here, and just live with a marginally less ergonomic thing until we have custom merge functions. I think I should survive having to explicitly call a function :stuck_out_tongue:
