### ISSUE TITLE
Stack overflow on a rather big, but not deep record.

### ISSUE THREAD

**Issue by YorikSar** [tweag/nickel#1427]
**Describe the bug**

I've been playing with generating `.ncl` file with `nixpkgs` metadata, and got stack overflow when trying to evaluate it with Nickel.

**To Reproduce**

When in try to evaluate [result.ncl](https://github.com/tweag/nickel/files/11937153/result.ncl.txt), I get this with current master:

```
 % nix run github:tweag/nickel -- export -f result.ncl

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
zsh: abort      nix run github:tweag/nickel -- export -f result.ncl
```

I tried removing some lines from it, and at some point the overflow doesn't happen anymore. I can provide a bigger example with all of nixpkgs data (5 Mb) if needed.

**Expected behavior**

It shouldn't fail, it should generate JSON output.

**Environment**
 - OS name + version: macOS Ventura 13.4.1
 - Version of the code: `github:tweag/nickel/b1458762817c1711e1502d5da6cde2df38edf54b`

**Additional context**

**Comment by vkleen** [comment]
A very quick look with `gdb` indicates that the stack overflow happens after a long list of calls to closures during import resolution. Specifically the traversal infrastructure at `core/src/term/mod.rs:1506` seems to build a huge call stack.

**Comment by yannham** [comment]
Yes, I suspected this would hit us some day. I like the simple, recursive definition of traverse. We can probably get away with traversing types, but traversing a whole term is more problematic. That being said, It's a bit surprised that this happens on a flat record; the callstack's size should be linear in the depth of the term being traversed, not its size. @vkleen does the stack trace happen to show, by any chance, which transformation is the culprit?

**Comment by vkleen** [comment]
As far as I can tell, it seems to happen during import resolution. It's also worth noting that the release build works fine, if pretty slowly.

**Comment by vkleen** [comment]
I think the issue with this particular term is that it includes a lot of definitions like `emacsPackages.bluetooth = ...`; so we're building up a huge merge term. That behaviour artificially inflates the depth of term.

**Comment by yannham** [comment]
> As far as I can tell, it seems to happen during import resolution

There are no imports, so import resolution is just traversing the term, leaving it unchanged. This sounds like it's not an issue of two transformations that could interact and unduly inflate the size of the term, as we had had. It's just the first full traversal to happen.

> I think the issue with this particular term is that it includes a lot of definitions like emacsPackages.bluetooth = ...; so we're building up a huge merge term. That behaviour artificially inflates the depth of term.

Oh, I didn't think of that. So the depth of the term is actually linear in the number of `emacsPackages.xxx` entries. Now this sounds like a plausible explanation. Thanks for the report.

I guess the obvious fix is to make `traverse` use a constant stack size with a growing stack + a loop instead of a recursive function. I still dream of the day when we can write a naive and easy to read recursive function, but just slap a `#[use_heap]` to generate code which doesn't blow the stack ([decurse](https://github.com/wishawa/decurse) does something like that, but it does have a cost in performance, and has a number of limitations)

**Comment by yannham** [comment]
Another unrelated optimizations could be to do the merge of subrecord ahead of time, instead of delegating to the runtime, when like this example, those are just combining disjoint record literals.

**Comment by YorikSar** [comment]
Indeed, if I avoid "dot-notation" (or field paths?) and thus avoid merges, the full nixpkgs export works just fine.
[full_nixpkgs.zip](https://github.com/tweag/nickel/files/11938126/full_nixpkgs.zip)

**Comment by YorikSar** [comment]
Sorry, that file didn't include nested packages. Here's the full file:
[full_nixpkgs.zip](https://github.com/tweag/nickel/files/11938161/full_nixpkgs.zip)
