### ISSUE TITLE
Improve readability of error messages

### ISSUE THREAD

**Issue by ad-si** [tweag/nickel#1764]
Right now the actual error message is quite easy to overlook. There is quite a lot of ASCII art going on, but the actual message text itself is not very prominent:

```txt
error: contract broken by the value of `arguments`: Incorrect values for argument JOURNAL_FILE: Arguments of type List-Text must always be optional
    ┌─ /Users/adrian/Dropbox/Projects/Transity/cli-contract.ncl:66:7
    │
 66 │     | NotRequiredIfList,
    │       ----------------- expected type
    │
    ┌─ /Users/adrian/Dropbox/Projects/Transity/cli-spec.ncl:129:19
    │
  1 │   let journalArgs = [
    │ ╭───────────────────'
  2 │ │   {
  3 │ │     name = "JOURNAL_FILE",
  4 │ │     description = "Path to the journal file",
    · │
 12 │ │   },
 13 │ │ ]
    │ ╰─' evaluated to this expression
    · │
129 │         arguments = journalArgs,
    │                     ^^^^^^^^^^^ applied to this expression
```

Just a little more spacing and line wraps would already help a lot:

```txt
ERROR:
Contract broken by the value of `arguments`:
Incorrect values for argument JOURNAL_FILE: Arguments of type List-Text must always be optional


    ┌─ /Users/adrian/Dropbox/Projects/Transity/cli-contract.ncl:66:7
    │
 66 │     | NotRequiredIfList,
    │       ----------------- expected type
    │
```

Also: I had to set `--color=always` as automatic detection didn't seem to work. Maybe because I was piping the result into a file? But stderr still goes to the terminal if you only pipe stdout, so color shouldn't be deactivated, right?

**Comment by vkleen** [comment]
I think the color issue you mention is caused by us checking if `stdout` is a terminal, instead of checking `stderr` in https://github.com/tweag/nickel/blob/28b6c719056b5e93751612bcfed8f43427948076/core/src/error/report.rs#L41. I'll try to fix that part quickly, at least.

**Comment by yannham** [comment]
Unfortunately we're constrained by the error reporting library we're using. Of course that is not a good reason, but on the other hand, I believe this library reflects how most of modern error reporting works: a clear color and severity (`error`), followed by a not too long and to the point description of what went wrong, and then more detailed data (locations, notes, suggestions, etc.).

I agree that trying to cram the severity, the "contract broken by the value of `arguments`", and the (arbitrary-long) custom contract-defined error message doesn't work that well.

I see several possibilities:

1. Maybe something as simple as adding new lines, as you suggested, in the main label of the error, might go a long way (the example message is a test for terminal escaping, so it's not very meaningful)
    ````diff
    -error: contract broken by a value: strike through with background "and" "quotes"
    +error: contract broken by a value
    +       strike through with background "and" "quotes"
    ````
2. Add the custom error message as a note. Pros: notes are made for that and it's fine to put long messages in there. Cons: the message would appear after the snippets, and thus not as prominent as today.
    ````diff
    -error: contract broken by a value:  strike through with background "and" "quotes"
    +error: contract broken by a value
       ┌─ [INPUTS_PATH]/errors/blame_custom_message_ansi_escaping.ncl:3:1
       │
     3 │ null | std.FailWith "\x1B[9;33;47m strike through with background \"and\" \"quotes\""
       │ ^^^^   ------------------------------------------------------------------------------ expected type
       │       
       │ applied to this expression
    +  │
    +  = strike through with background "and" "quotes"
    ````
   (obviously, we would need to escape terminal control sequences)
3. We can generate several diagnostics. So we could split the diagnostics between one the "error: contract broken by the value of `arguments`", and a second one with the custom error message and locations. Maybe this one should be a "note" severity, otherwise it would look like it's a second, different error.

I think 1. looks good, and is a very small change. The only thing is that error messages can also be produced as JSON for processing by other tools, so trying to include custom indentation in there might not render great if the error is say serialized in python to be displayed in a webapp. But it's not a hard blocker, of course.

**Comment by yannham** [comment]
Let's go with solution 1 for now (cf #1767), it's cheap and it makes things better already. We can revisit later, error messages layout changes aren't breaking anyway.
