### ISSUE TITLE
Creating parent directories when exporting

### ISSUE THREAD

**Issue by a12l** [tweag/nickel#1784]
**Is your feature request related to a problem? Please describe.**

The first time I want to export an application configuration it may happen that the configuration's parent directory hasn't yet been created.

```console
$ printf '"Hello, World!"' > bar.ncl

$ ls
bar.ncl

$ nickel export bar.ncl --format raw --output ./foo/bar
error: No such file or directory (os error 2)

  nickel export bar.ncl --format raw --output ./foo/bar
  ^~~~~~
```

This problem most often occur on new machines and when deploying new applications.

**Describe the solution you'd like**

Add a `-p | --parent` flag that tells Nickel to create the necessary parent directories if they don't already exist, similar to `mkdir`.

**Describe alternatives you've considered**

Writing a shell function for every application that is executed first to check if the parent directories exists, and if necessary create them.

**Additional context**

No other context that I currently can think of.

**Comment by yannham** [comment]
At first sight, I'm a bit skeptical, as I reckon ensuring that the directories exist shouldn't really the responsibility of `nickel`, and because as you mention, it's rather easy to do by just adding `mkdir -p ./foo && nickel export bar.ncl --format raw --output ./foo/bar`.

Do you know of other tools similar to Nickel (anything producing export files, for example) which provide such an option?

**Comment by yannham** [comment]
Thanks for proposing something new! However, unless there is new evidence for such a feature, I'm closing for now as I don't think it's really in scope for a language interpreter, and because there are simple ways for creating missing directories outside of Nickel using basic Unix tooling.
