### ISSUE TITLE
Improve parser heuristics: find reference of a symbol in outer scope when the symbol is identical to the record field the symbol is referred at

### ISSUE THREAD

**Issue by suimong** [tweag/nickel#1785]
**Is your feature request related to a problem? Please describe.**

Here is a contrived illustration:

```
{
  a = 1,
  b = 2,
  foo = {
    c = 2,
    d = 3,
    bar = {
      c = c+1,  # this creates a circular reference at the moment, but ideally `c` could refer to `foo.c`
      c' = foo.c + 1,  # this is the current workaround,
      a = a + 2, # similar to c, but ideally `a` could refer to the outermost `a`
    }
  }
}
```
In the example of  `bar.c`, I can't seem to find a counter-example in which by referencing `c` in a particular way (denoted `f(c)` for convenience) would not lead to `bar.c = f(c)`  being a circular reference. Thus, if referencing `c` in `bar.c` always leads to circular reference, then I guess the parser could do the "smart" thing by finding reference to `c` in an outer scope, which would lead to better and more intuitive developer ergonomics, and  #1777 would also be solved.

**Comment by yannham** [comment]
Thanks for the suggestion. I agree that the current unconditional capturing of siblings - or even the field being defined itself - is a usability issue that needs a good solution, which isn't there yet, unfortunately.

That being said, I see potential issues with the solution proposed, at least as it is:

- because of lazyness, circular references don't necessarily lead to loops. A stupid example would be `c = let first = fun x y => x in first 5 c`. Of course, it's not very useful to write such a thing, but maybe there non obvious examples of recursive usages that are legitimate, even for primitive values.
- a more concrete example of useful circular references is for functions: `std.array.fold_xxx` used to be defined recursively in the stdlib using such an auto reference (now an auxiliary recursive functions is defined inside for entirely orthogonal reasons)

This wouldn't be an absolute hard blocker, but I think it leads to the next point: it seems that right now, there's no obvious, dead-simple condition that can be grokked and decided immediately to say "this is an auto reference" or "this actually refers to an outer field". Thus, implementing any kind of non trivial rule in the parser is dangerous IMHO, because this means the reader of a Nickel file will have to apply the same rule to understand a program. Especially a newcomer or a sysadmin that might not know the language that well, if at all.

If the parser is to disambiguate such references, the rule must really be _very_ obvious, in a way such that people should be able to come up with the rule by themselves. I'm not entirely sure this is the case here.

**Comment by suimong** [comment]
Totally agree. In fact I do have a vague feeling that something exists that would break the premise of my suggestion, and kind of counting on you to provide the examples, and the first bullet point is a really nice one. As for the second bullet point, I have actually been taking advantage of "auto reference" to write recursive functions for quite a while but just couldn't connect the dots when contemplating this issue.

As always thanks @yannham for your wonderful explanation.
