### ISSUE TITLE
NLS reports same diagnostic message multiple times

### ISSUE THREAD

**Issue by uhlajs** [tweag/nickel#1882]
**Describe the bug**

NLS reports same diagnostic message multiple times when the recursive definitions is present. Related to #1875.

https://github.com/tweag/nickel/assets/13243167/dca92462-5493-4891-aa1a-83765bb27518

**To Reproduce**

```nickel
{
  applications = {
    apps | not_exported = applications,
    message = "message",
    blah | String = 5,
  }
} 
```

**Expected behavior**

The diagnostic message will be reported only once per case.

**Environment**
 - OS name + version:

```
NAME="Fedora Linux"
VERSION="39.20240327.0 (Sericea)"
```

 - Version of the code: [262ac8fa36df3268414750094ddaa358344decf2](https://github.com/tweag/nickel/commit/262ac8fa36df3268414750094ddaa358344decf2)

**Comment by yannham** [comment]
I wonder what's the best way to avoid this case in the recursive setting. I think @jneem mentioned somewhere that it's not as simple as black-holing or marking fields to not re-evaluate them many times (otherwise we would do that instead of having a max evaluation depth, and also because I guess one field might end up having different copies in different merge expressions, and thus with a different environment).

Maybe just compute a cheap hash of diagnostics and de-duplicate them is the easiest way forward.

**Comment by yannham** [comment]
(Or, put differently, store the diagnostics in an ordered set [or maybe we don't event care about ordering?] with a cheap hasher instead of a vector)

**Comment by jneem** [comment]
Sort + deduplication is probably the way to go. We do this for some responses, just because it makes the output deterministic and therefore easy to test. But apparently we aren't (yet) doing it for diagnostics.
