### ISSUE TITLE
Evaluate to JSON

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#196]
**Is your feature request related to a problem? Please describe.**
To start experimenting on small but real-world examples with Nickel, one needs to be able to generate JSON (and, later, other targets as well such as YAML, TOML, etc.) from the evaluation of a program.

**Describe the solution you'd like**
The evaluation of a program, either via the current nickel executable, or using a different executable for now such as `nickel-json` (in the medium term, the target will probably just be an option of the main one), outputs the result as a valid JSON document.

**Comment by aspiwack** [comment]
Just for the record: I highly doubt the value of a separate executable with almost the exact same code just because the last few lines of code executed are different. So I'd advocate for one executable which can do the json output, as well as the type checking in the same executable. (probably with git-style subcommands)
