### ISSUE TITLE
Make record pattern matching recursive

### ISSUE THREAD

**Issue by ajbt200128** [tweag/nickel#1989]
**Is your feature request related to a problem? Please describe.**
I am currently working on the nix -> nickel transpiler PR over in this branch https://github.com/ajbt200128/nickel/tree/nix/nickel. One issue is that nix supports recursive pattern matching in record patterns:
```nix
let f = { x ? y, y ? x}: x + y; in f { x = 1; }
> 2
```
But nickel does not
```nickel
let f = fun { x ? y, y ? x} => x + y in f { x = 1 }
  ┌─ <repl-input-0>:1:26
  │
1 │ let f = fun { x ? y, y ? x} => x + y in f { x = 1 }
  │                          ^ this identifier is unbound
```

**Describe the solution you'd like**
It would be great if we emulated this behavior in nickel, as it make pattern matching more powerful, and would be more consistent since records can already be recursively defined in a normal definition. Additionally it will make the nix transpiler easier to write

**Describe alternatives you've considered**
We could desugar this in only the transpiler, but that will require repeating a bunch of the pattern matching code that already exists in nickel

**Comment by yannham** [comment]
I think we need to ponder if making recursive patterns the default is a good thing for Nickel, independently from the needs of the Nix transpiler. From the top of my head, the semantics doesn't look to convoluted: I guess the idea is to say that the record being destructured brings its fields into the scope of default values as well.

One bit that worries me is that you can now introduce infinite recursion with a pattern. Here is a Nix example:

```nix
nix-repl> f = { x ? y, y ? z, z ? y}: [x y z]

nix-repl> f {}                                
[ error: infinite recursion encountered

       at «string»:1:15:

            1|  { x ? y, y ? z, z ? y}: [x y z]
```

While the error is simple here, infinite recursion can have the bad taste of being much harder to fix if there's more indirection (or to even not error out but just loop for ever, especially in Nickel, which uses a stack machine)

**Comment by ajbt200128** [comment]
That's true it allows infinite recursion, but this is still possible in nickel:
```nickel
let f = fun record =>
  let default_values = { x | default = y, y | default = z, z | default = y} in
  record & default_values
```

returns
```nickel
nickel> f {}
error: infinite recursion
  ┌─ <repl-input-11>:2:74
  │
2 │   let default_values = { x | default = y, y | default = z, z | default = y} in
  │                                                                          ^ recursive reference
```
So, users can still encounter almost exactly the same behavior in nickel that happens in nix, it's just not in the pattern matching syntactic sugar. So I don't think allowing this would make nickel less correct. But what about debugability?


I think the error messaging around pattern matching in the parameters is already pretty good, for example:
```nickel
let f = fun {x ? 1, y ? 2, z ? my_unbound_identifier} => x + y + z
```
is allowed, but once you call `f`:
```nickel
f {}
error: unbound identifier `my_unbound_identifier`
  ┌─ <repl-input-23>:1:41
  │
1 │ let f = fun {x ? 1, y ? 2, z ? my_unbound_identifier} => x + y + z in
  │                                ^^^^^^^^^^^^^^^^^^^^^ this identifier is unbound
```
is very clear to me.

I can be swayed either way, but in general I lean towards a language being more internally consistent. E.g.
```nickel
let f = fun {x ? y, y ? z, z ? y} => x+y+z
```
resulting in
```nickel
f {}
error: unbound identifier `y`
  ┌─ <repl-input-29>:1:32
  │
1 │ let f = fun {x ? y, y ? z, z ? y} => x+y+z in
  │     
```
is confusing to me when I could do this in the other way I presented previously, where
```nickel
f {}
error: infinite recursion
  ┌─ <repl-input-29>:1:32
  │
1 │ let f = fun {x ? y, y ? z, z ? y} => x+y+z in
  │                                ^ recursive reference
```
would be much clearer to me as a user

**Comment by yannham** [comment]
> That's true it allows infinite recursion, but the nix behavior is still possible in nickel:

Sure, Nickel is Turing-complete. It is expected that functions and recursive records can lead to infinite loops. This adds yet a new way of causing infinite recursion though, and it's a bit surprising IMHO that this can happen in a pattern matching, which is usually just a fancy branching construct (for the record example, you need merging for example, which is expected to do complex computations and to build recursive bindings).

All of this to say, I'm not saying this is hard blocker, but it's not free either in term of complexity added to the language. I'm curious as to how much this feature is used in Nix.

Otherwise, I just had a random idea: for now, just for the sake of desugaring, could you split such recursive patterns as a contract and a pattern? For example:

`let f = {x ? y, y ? z, z ? x}: body; in rest` => `let f | {x | default = y, y | default = z, z | default = x} = fun {x, y, z} => <translation of body> in <translation of rest>`. There might be some semantics differences, in particular in the presence of aliases. In fact, before the full blown pattern matching implementation, a destructuring let like `let {x ? 1} = {} in ...` would be elaborated as a contract and a let-binding in Nickel, basically : `let __tgt | {x | default = 1} = {} in let x = __tgt.x in ...`. I think the only difference (but I have to think hard about it to make sure) with the current semantics is with aliases: `let root @ {x ? 1} = {} in rest` currently assigns `root` to `{}` (and I believe this is the semantics in Nix as well), while with the contract approach `root` would inherit the default value and be `{x | default = 1}`. The second difference is the additional `default` priority, but since Nix has no notion of priority or merging, that shouldn't matter for the image of the transpilation from Nix.

**Comment by ajbt200128** [comment]
yea that's fair, it is more unexpected when the pattern matching is relatively simple compared to merge. I guess my point is from the point of view of a user of the language, I would expect pattern matching to be similar to constructing a record. On the other hand though, I do think your point re: complexity is fair. We're adding complexity for a relatively obscure behavior people probably wont use anyways. At least, I don't see this a lot in nix. So I'm ok with leaving this issue open for others to comment, but I've been convinced that this feature may not make sense to add for now.

I think this contract approach is a good stop gap though, there's probably not that much nix code that the first difference will pop in so I'm ok not worrying about that

**Comment by yannham** [comment]
A second, maybe better argument mentioned in the weekly yesterday: it's actually backward-incompatible, unfortunately, because now the bindings of the record take precedence over what's been in the environment:

```nickel
let x = "foo" in
match {
  {x, y ? x} => ...
}
```

The result of this will change between now and an hypothetical version with recursive patterns.

That being said, I love that you're pursing the Nix transpiling and don't want to make your life harder @ajbt200128. As long as it's not user-facing, we can very much add a special primop which is a variant of `match` but with the Nix semantics, just for the sake of transpiling. I'm very much not opposed at having the logic in core Nickel, if it's not visible to normal users. I guess we could reuse much of the pattern matching compilation, but just pass an additional "flavour" argument or whatever that would change how default values are handled

**Comment by ajbt200128** [comment]
Oh good call re: backwards compatibility, going to close this because I think that this isn't worth a breaking change like that. I'll just try and add a nix specific version of match that is hidden from users and only used for transpilation, based off the contract approach you mentioned, or maybe a modified version of the pattern matching compilation. Thanks!
