### ISSUE TITLE
Record row polymorphism can be destructive

### ISSUE THREAD

**Issue by cydparser** [tweag/nickel#2014]
**Describe the bug**

A function with type ` forall tail. { a : Number ; tail } -> { a : Number ; tail }` can remove the record tail from the returned value.

**To Reproduce**

Evaluate the following expression:

```nickel
let f : forall tail. { a : Number ; tail } -> { a : Number ; tail }
  = fun o => o
  in f { a = 1, b = ".." }
```

The result is `{ a = 1, }`.

**Expected behavior**

I expect a result of `{ a = 1, b = ".." }`.

**Environment**
 - OS name + version: Windows 11
 - Version of the code:  master (a7dc3594)

**Comment by yannham** [comment]
This hasn't been caught earlier, which is embarrassing. This bug was already present in 1.7. It seems to be related to the contract elision optimization (which avoids some dynamic check when a function is statically typed), because turning the type  annotation to a `|` works as expected.

Having fields that mysteriously disappear from your record silently is surely not going to be fun to debug. Thanks a lot for catching this, will include a fix in the imminent 1.8 release.
