### ISSUE TITLE
Recursion by default is hazardous

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#216]
Writing the very first "serious" example (cf [the experimentation repo](https://github.com/yannham/guestbook-go-nickel)) in Nickel, I started with a seemingly benign snippet:
```
let name = "guestbook" in
{
  name = name;
  ...
}
```

But the first run went into an infinite loop, because records are recursive by default (see https://github.com/tweag/nickel/issues/83#issuecomment-646621649). I would like to advocate in general that recursion by default is too aggressive:

- recursion is often not what you want, but rather you want multiple variables to depend on one source of truth. You can hoist up this source of truth to a let-bound variable and eliminate self reference totally. Recursive record are listed as an anti-pattern by the [Nix documentation](https://nix.dev/anti-patterns/language.html#rec-expression) which mention the same elimination technique. Recursive records have usages, e.g. when you want your configuration to be extensible by overriding, but I don't think this mandates to make it the default.
- it pollutes the environment. If you are in a sub-sub-sub record (which may not be that uncommon, in big configurations), you inherit a lot of recursive variables that are as many potential traps.
- it currently has a performance/memory cost paid by all records, even those that don't have self references, although this is rather due to the current implementation being not optimal than an intrinsic limitation.
- explicit is, if not always, often better. Coming from OCaml, the mandatory `rec` keyword (and associated errors/warnings on misuse) saved me multiple times from either infinite loops or incorrect implementation (but that would have silently compiled otherwise, typically, forgetting the recursive call in a loop). I know some Haskellers feel the same, and wished bindings were not recursive by default in Haskell.

I would rather go with explicit recursion at usage site, using something like a `self` keyword, which immediately distinguishes a normal variable from a self referent one, and add very little noise. This is the solution chosen by [Jsonnet](https://jsonnet.org/learning/tutorial.html#references), which has the closest model in term of recursive records (or, dare I say, objects). Doing so, a nested record cannot directly accesses an enclosing record, so Jsonnet also have a `super` keyword and co. But in simple cases it is not even required, as one can captures `self` in a let-binding:

```
{
  nested = let super = self in { foo = super.bar ++ self.foobar; foobar = "world!" };
  bar = "Hello, ";
}
```

All in all, I think implicit, by-default recursion has a lot of drawbacks for very little benefits (saving a `rec` or `self` word here and there), but I would like to gather the opinion of other people on this.

**Comment by aspiwack** [comment]
Yet another possibility is `rec`-as-a-binder. That is you'd write `rec (self)` and bind `self` in the record, or `rec (me)` or `rec (here)` or whatever. So you could choose the name of the binder so as not to interact with other records.

I don't really have a strong opinion on this particular issue. In programming languages, I most definitely agree that recursive-by-default is not great (though, to be fair, recursive-by-default together with a way to bind non-recursively is not that bad). But, for a configuration language, I don't know. I think both options have something to speak for.

That being said, it is true that one of the goal of Nickel was to de-emphasize recursion because it is often not needed and complicates package indexing and such. Much in the spirit of the non-Turing-completeness crowd. So according to this goal it would be good to mark recursion explicitly.

On the other hand, Cue does allow self-references in records by default, it is just not interpreted as recursion. Could we have a similar feature? Your case would probably still give an error though (but not an infinite loop). But it has an opportunity to be a best-of-both-world situation.

@edolstra what do you think?

**Comment by yannham** [comment]
> On the other hand, Cue does allow self-references in records by default, it is just not interpreted as recursion. Could we have a similar feature? Your case would probably still give an error though (but not an infinite loop). But it has an opportunity to be a best-of-both-world situation.

That's an interesting idea. We could decide that by-default self reference semantics requires the dependency graph to be a DAG, so that you could actually get rid of these self references if you wanted to. But this wouWe would require a `rec` or whatever keyword for general recursion. Somehow recursive references would have a unification-based semantics rather than evaluation-based. In practice we probably want to keep the same implementation, so this amounts to have a simple termination checker.

One nice property is that while merging can change the value of the nodes in the dependency graph (more precisely, it can replace a leave with another graph), it can't break the DAG property (the substituted graph cannot have back edges to the parent's graph). So this well-foundedness wouldn't have to be re-checked at each merge.

It is theoretically less powerful than merging + general recursion. You can safely refer to the parent's previous state using explicit binding:

```
let base = {
  name = "base";
  url = "http://server.com/{name}"
  ...
}

base & {name = "derived"} // url is correctly updated
```

What you can't do is to refer to a parent field, that itself depends on a field you redefine, as in:

```
let base = {
  name = "base";
  version = 2;
  url = "http://server.com/{name}"
  ...
}

base & {name = "derived"; fooUrl = self.url ++ "?version=" ++ self.version} //Not possible to express
```

I don't know how much in practice you need the latter case. This is questions for Nixers.

**Comment by edolstra** [comment]
I'm not so sure. In NixOS modules, we're constantly prefixing everything with `config.`, which is a consequence of the fact that the NixOS module system is not implemented as a language feature. In a proper DSL for configuration management, you wouldn't want to have to write those superfluous `config.` prefixes.

The example
```
let name = "guestbook" in
{
  name = name;
  ...
}
```
could be addressed by disallowing name clashes between lexical scopes. Then, rather than an infinite recursion, you'd get an error like "`name` at line 3 clashes with `name` at line 1".

BTW, slightly parenthetical, but it has been suggested (in the context of Nix modules) to get rid of let-bindings, since they're not overridable. Putting configuration in a let-binding (as in `let name = "guestbook"`) could be seen as an anti-pattern since there is no way for callers to override `name`.

**Comment by yannham** [comment]
> could be addressed by disallowing name clashes between lexical scopes. Then, rather than an infinite recursion, you'd get an error like "`name` at line 3 clashes with `name` at line 1".

Yes, forbidding shadowing would work for let/record conflicts. In this precise case we should probably use thunk blackholing anyway to detect this kind of infinite loops.

> BTW, slightly parenthetical, but it has been suggested (in the context of Nix modules) to get rid of let-bindings, since they're not overridable. Putting configuration in a let-binding (as in let name = "guestbook") could be seen as an anti-pattern since there is no way for callers to override name.

Right, I'm trying different style on this example. The previous example is Nixpkgs-style functional style, where a function takes the variable data and generates a record. Using a more NixOS/CUE-like approach based on merging, another annoyance appears with nested record + recursive records:

```
{
  role = Contract(Str);
  ...
  metadata = 
      { role = ? // would like role = super.role
        ...
      }
```

This is also a name clash, but there you don't get to chose the names of the attributes. You can still do:

```
{
  role = Default("master");
  ...
  metadata =
      let role_ = role in 
      { role = role_ // would like role = super.role
        ...
      }
```

but it's not great either, especially if you have a lot of attributes to use from your parent at multiple places. It already happens multiple times in the small Kubernetes example, as several pieces of a data are repeated at several levels.

**Comment by Profpatsch** [comment]
> ```
> 
> ```
> 
> 
> What you can't do is to refer to a parent field, that itself depends on a field you redefine, as in:
> 
> ```
> let base = {
>   name = "base";
>   version = 2;
>   url = "http://server.com/{name}"
>   ...
> }
> 
> base & {name = "derived"; fooUrl = self.url ++ "?version=" ++ self.version} //Not possible to express
> ```

Can you elaborate on that? I don’t quite see where the problem is here.

**Comment by mboes** [comment]
> could be addressed by disallowing name clashes between lexical scopes. Then, rather than an infinite recursion, you'd get an error like "name at line 3 clashes with name at line 1".

If we did that we would also need a way to delete stuff from the scope, so that a name can be reused for a record field. Or we could say that in that case, just quote the record name.

**Comment by yannham** [comment]
@edolstra made pretty clear that he thinks recursion by default is the right choice. Also, these cases are now mitigated partially by #276, which detects this kind of direct infinite recursion. Unless someone has something more to say, I'm closing for now.

**Comment by silverraven691** [comment]
Have you considered adding syntax like Rust's [short-hand field initialization](https://rust-lang.github.io/rfcs/1682-field-init-shorthand.html)? This could function as the original post intends to express it:
```nickel
let name = "hello" in
{
  name,
  version = "1.5.3",
}
```

Sorry to intrude on an issue closed a while ago, let me know if you'd rather I open a new issue.

Thanks.
