### ISSUE TITLE
Please explain more about the decisions behind syntax and side effects

### ISSUE THREAD

**Issue by ryepesg** [tweag/nickel#223]
**Is your feature request related to a problem?**

There are already too many programming languages, why to start designing a new syntax from the scratch? The problems I see are:
- Nobody gets syntax right the first time, which means either warts or backwards compatibility issues (e.g Python3, HCL2)
- Impact in adoption, since the syntax will be foreign for the 100% of the people
- Additional context switching to work with other programming languages
- Small standard library, so users end up re-inventing the wheel

**Describe the solution you'd like**

It would be useful to have additional documentation explaining some of the design decisions, including:

-  What is the main reason for Nickel to support side effects? Is the focus being in provisioning infrastructure like HCL / Pulumi / AWS CDK?

- Why start from scratch for the design of the syntax instead of reusing the one from existing languages?

- Are there plans to increase the size of the standard library or support something similar to [Dhall prelude](https://prelude.dhall-lang.org))?

**Additional context**

Prior art in dynamic languages:
- Runtime data validation: [Clojure Spec](https://clojure.org/about/spec)
- Gradual typing: Pulumi Typescript and [Pulumi with Python type annotations](https://www.pulumi.com/blog/announcing-python-tooling-improvements/)

Example of modern ML syntax: [ReasonML](https://reasonml.github.io)

**Comment by mboes** [comment]
> There are already too many programming languages, why to start designing a new syntax from the scratch?

Fair question. To answer that, keep in mind that not all languages have the same *semantics*, so it's not like the same syntax can reasonably be expected to be effective everywhere, even though the cost of changing the syntax is high, as you point out. Starlark is also a a configuration language. It uses the Python syntax, in so small part due to the reasons you cite. It's also a language with no first-class functions, where functions are meant to be implemented as a sequence of statements. In contrast, Nickel encourages a different style, where instead of sequencing statements, the user is meant to compose functions.

This functional programming style is one that has already proven effective in the [Nixpkgs](https://github.com/nixos/nixpkgs) project. The Nix language has had mostly stable syntax for over 10 years, but it has no specification, and coming up with one that is 100% faithful would be hard. When experimenting with the new ideas behind the Nickel project, we chose to instead use a cleaned up version of the Nix styntax. Much like ReasonML did, which you cite, relative to OCaml.

**Comment by mboes** [comment]
Note further that this is an experimental language. The syntax could yet change to something completely different, including becoming some subset of an existing syntax.

**Comment by ryepesg** [comment]
I appreciate your answer, thanks for taking the time providing that context. I wish you great success with Nickel. I believe it has the potential to transform how the industry works in terms of infrastructure as code and reproducible builds. Keep up the good work!

**Comment by yannham** [comment]
Thanks for your kind words. I think you will find some answers to your question in the [RATIONALE](https://github.com/tweag/nickel/blob/master/RATIONALE.md#side-effects) document.

> * What is the main reason for Nickel to support side effects? Is the focus being in provisioning infrastructure like HCL / Pulumi / AWS CDK?

That is indeed some of the use cases of Nickel. The rationale is not to provide arbitrary or generic side-effects, such as opening files or sending packet through the network. Nickel would be mostly pure by default, but some specific usages require side-effects in one form or the other: the idea is to have the capability of extending the language with usage specific side-effects, such that you don't have to either switch to another technology or have to resort to ugly hacks in these situations.

> * Are there plans to increase the size of the standard library or support something similar to [Dhall prelude](https://prelude.dhall-lang.org))?

Sure, the standard library is currently being built and is very far from a final state. I don't know how close to dhall-preludes it will be, but it will surely cover the basic features one expect from a standard library.

**Comment by ryepesg** [comment]
Fantastic, that is great to know, looking forward to seeing how Nickel will look in the future!
