### ISSUE TITLE
Integers serialized as floats

### ISSUE THREAD

**Issue by edolstra** [tweag/nickel#309]
**Describe the bug**

Integer values are currently serialized as floats:
```
nickel> builtins.serialize `Json 123
"123.0"
```
While not strictly speaking incorrect, this may be confusing/annoying in contexts where an integer value is expected.

**Expected behavior**

Numbers that are an exact integer should be serialized without a trailing `.0`.

**Comment by yannham** [comment]
It seems there's no single satisfactory solution to do this using serde, because serialization is done in an intermediate representation format (in order to be compatible with multiple output format) which doesn't support arbitrary precision integers. Here are the options:
1. Convert floating point numbers to i64 or u64 whenever possible. This will solve this issue for floating point numbers representing integers that are in the range of a `i64` or an `u64`, but keep the trailing zero otherwise.
2. Use serde_json's formatter to achieve this. The Json serializer/deserializer support custom formatting which allows to do what we want, but this is only the case for `json`, and is not possible with YAML and TOML.
3. Combine the two, so that every number in the range of an u64 or i64 will uniformly be printed as an integer whenever possible, and even when outside of this range but only for JSON. This sounds like the most "featureful" option but introduces a discrepancy between JSON and other formats. Don't know if it's a problem.

**Comment by edolstra** [comment]
Option 1 sounds best since it would also work for the YAML and TOML serializers.
