### ISSUE TITLE
WSL1: Enable building executables for that platform as well.

### ISSUE THREAD

**Issue by 573** [tweag/nickel#344]
**Is your feature request related to a problem? Please describe.**
When I `cargo build` nickel on a WSL1 installation I'm getting
>bash: /nix/store/4vx76npl01pshqnyrx5gq2n92zslflvy-rust-1.49.0-2020-12-29-e1884a8e3/bin/cargo: cannot execute binary file: Exec format error

**Describe the solution you'd like**
A solution would be to have the executable built using WSL1 infrastructure.

**Describe alternatives you've considered**
Using WSL2 is recommended if feasible for users.

**Additional context**
The issue seems to be [known](https://github.com/microsoft/WSL/issues/5365) already on WSL side.

**Comment by yannham** [comment]
Thanks for testing and reporting, @573. I'm not familiar with WSL/WSL2. I'm not sure what to do, and what can be done at the level of Nickel here, since it seems this is a more general issue with Nix and WSL. Does a direct build, without going through Nix but using a system level Rust installation, work? Also, even if this hasn't been tested, I think Nickel uses portable libraries for the most, and may even build directly on Windows.
