### ISSUE TITLE
`default` values and contracts don’t compose properly

### ISSUE THREAD

**Issue by regnat** [tweag/nickel#402]
**Describe the bug**

When a value `bar` has a contract and a default value, and its default value itself has both a contract and a default value, then the default of the default value will be ignored, and only its contract will be applied.

**To Reproduce**

Evaluating

```
let
  myContract = { x | Str }
in
{
  foo | #myContract | default = { x = "From foo" },
  bar | #{..} | default = foo
}
```

results in

```
error: empty metavalue
  ┌─ /tmp/tmp.eYEzU3ur1v/test.ncl:4:18
  │
4 │   myContract = { x | Str }
  │                  ^^^^^^^ here
```

rather than the expected

```
{
  "bar": {
    "x": "From foo"
  },
  "foo": {
    "x": "From foo"
  }
}
```

Everything works fine if `bar` either doesn’t have a contract or has a plain type annotation (`bar | { x : Str } | default = foo`).

**Environment**
 - OS name + version: NixOS 21.05
 - Version of the code: 8ce9a90

/cc @yannham

**Comment by yannham** [comment]
We've briefly discussed this elsewhere, but just as self reminder for later:

Contract application of a contract-as-a-record used to be plain merging. Since closed contracts (#374), it's a different operator but it still shares most of the code and semantics. Thus, when we apply the outer contract `#{..}` (which is an empty record, as long as evaluation is concerned) to `foo`, the latter is thrown away because it is a default value (as if we would do `{ } & (foo | default)`). Then the second contract is applied, requiring `x`, and complains it is not defined.
Obviously record contract application should not take priority into account. It should probably be "strict" (in the sense, don't care about metadata) in its arguments. I'll just have to think about the right semantics a bit, to avoid pushing an ad-hoc fix to this particular situation.
