### ISSUE TITLE
Cyclic imports make the interpreter loop

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#409]
**Describe the bug**
Cyclic imports make the binary overflow its stack. It's not evaluation, as it already happens just with typechecking. Spotted because of #407.

**To Reproduce**

```
echo 'let x = import "b.ncl" in null' > a.ncl
echo 'let x = import "c.ncl" in x' > b.ncl
echo 'let x = import "b.ncl" in x' > c.ncl
nickel -f a.ncl typecheck
```

**Expected behavior**
The program should evaluate successfully on `null`. Cyclic imports shouldn't be a problem. They weren't originally.

**Environment**
 - OS name + version: Linux 5.10.0-8-amd64 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
 - Version of the code: 269ead2a58ded6b1939e70dcd23550e92304277f

**Additional context**

A git bisect shows that the offending commit is b029763736dfa954e82bc65370b35c24117f6848
cc @francois-caddet

**Comment by francois-caddet** [comment]
It looks more like a typechecking issue.
In this case we can neither check b.ncl nor c.ncl.
To options:
- do not typecheck an import if not used by the right side of the `in`. We could even not resolve the import in this case
- evaluate the import `import "b.ncl"` to null.

The first option is probably the best because, if  in a.ncl we have `let x = import "b.ncl" in x` x does not have type nor value. So it's preferable to throw an error in this case. Something like: Can not evaluate x due to cyclic assignation on itself. Probably easy to implement in this case but could be more tricky in others. for instance:
```Text
// a.ncl
let b = import "b.ncl" in (let c = import "c.ncl" in b.x + c.x)

// b.ncl
let c = import "c.ncl" in {x=c}

// c.ncl
let b = import "b.ncl" in {x=b}
```

**Comment by yannham** [comment]
You're right that it is because of typechecking: it basically doesn't remember the imports it traversed, so it just goes over the same imports again and again. However cyclic things are not a problem to handle, typechecking-wise:

```
{ foo = bar + 1, bar = foo + 1 } : {foo : Num, bar: Num}
```
typechecks without issue. Evaluation loops are something different, we just can't detect them in general, and a simple case of cyclic imports should already be detected at runtime. 

So in the case of this issue, we just have to remember an environment of visited imports, to avoid typechecking the same import more than once.
