### ISSUE TITLE
Rename List to Array or Vector

### ISSUE THREAD

**Issue by mboes** [tweag/nickel#533]
**Is your feature request related to a problem? Please describe.**
Nickel lists are not lists in the sense that functional programming understands them (a datatype with inductive structure, effectively a linked list). I believe the same remark holds regarding Nix. The algorithmic complexity of operations like `elem_at` are not what one would expect, while `tail` might either take more time or leak memory. @aspiwack noted very early in the design of Nickel that lists are a misnomer. Though not likely, we may well want a list type too down the road, in which case it would be better for `List` not to mean array.

**Describe the solution you'd like**

Change the type primitive type `List` to `Array` or `Vector`. Either is fine I think. "Array" is the term used in JavaScript and other configuration languages like CUE. "Vector" is perhaps more specific to C++, Rust, Haskell (the latter uses both terms for essentially the same thing), but perhaps rolls off the tongue better.

**Additional context**

ReScript [is an example](https://rescript-lang.org/docs/manual/latest/array-and-list) of a language that draws the distinction between lists and arrays as we do here.

**Comment by aspiwack** [comment]
Json's terminology is “array”. It's probably best to stick to it.

**Comment by yannham** [comment]
One detail that comes to mind is that we discussed at some point the fact that because of contracts, most list operations are unexpectedly linear in the size of the array (such as `head` or `elemAt`), which is not great. One straightforward way to avoid this is to precisely to use Haskell-like lazy linked lists instead, at the price of different performance characteristics. It's probably not the only way (we could do something similar for arrays I guess, with some sort of lazy contracts for arrays, but this would require ad-hoc runtime support). Let me put this in a separate issue.

As for having both array and lists, I feel like this may be slightly overkill for a configuration language. We should probably choose one representation that works well for our use-cases and with contracts, and stick to it.
