### ISSUE TITLE
Let me generate some markdown documentation

### ISSUE THREAD

**Issue by silverraven691** [tweag/nickel#650]
**Is your feature request related to a problem? Please describe.**
In order to consult the stdlib's documentation, I have to read its source

**Describe the solution you'd like**
I'd like to be able to generate just enough markdown from the metadata of values (such as the stdlib, but not only) in other to stitch together a documentation page.

I think this could be implemented cheaply for now, piggy-backing off `nickel query` and `QueryPrinter` in `src/repl/query_print.rs`, maybe adding a flag to use `SimpleRenderer` instead of `MarkdownRenderer`. From there, it'd be fine to concatenate a big document together from multiple calls, perhaps as Nix expression.

I'm happy to provide some PRs if this is accepted.

**Describe alternatives you've considered**
- Formats other than Markdown would be fine, it's just ubiquitous
- We could make `nickel query` emit JSON and people could format the documentation however they want, that doesn't seem insanely helpful as the documentation strings would still be markdown
- We could start a `nickel doc` and generate full blown docs, similarly to `cargo doc`, but that seems like a lot of work with the more-structural-than-nominal approach of Nickel, and we're still dealing with some instability
- Add metadata introspection capability to the language in order to generate the documentation via exprs, I doubt that's enough of a justification though

**Comment by yannham** [comment]
I guess you will have to do something about the nesting of headings, other just concatenating could give something like:

```markdown
# Record module

## insert

... doc of insert...

# Examples

examples of insert

## update

etc..
```

Maybe there are some CLI out there that can do to do this, or it's simple to implement ("shifting" all the headings by some nesting level).

Beside that, generating doc was our the radar, and I think we can have something working without much effort indeed. To be debated, but even a markdown generator could go as `nickel doc`, or at least `nickel doc --format markdown` so that we can keep future `nickel doc` for html by default, if needed.

Roughly, the plan to generate something from `nickel doc -f foo.ncl --format markdown` would be:

- `eval_full` the program
- traverse the result. There shouldn't be anymore `let-binding` and stufff, but only values (technically weak head normal forms: basic data types, records, lists, functions, metavalue).
  * If you encounter a record or a metavalue with a record inside, render the potential documentation/types/contracts (as query printer), list the fields and recursively do the traversal to generate the doc of each field.
  * If you encounter any other value (potentially wrapped in a metavalue), print a representation (like the one printed by evaluation) and the potential doc/type/etc. inside. Maybe we want to print the doc of list elements in the future, but for now, let's say we don't.
 
With the caveat of headers shifting. In some sense this is close to what `query_printer` does, but it would just be recursive when called on record fields. As you say we may be able to reuse some of the existing `query` infrastructure.

I would be happy to review PRs and to provide any support needed in order to implement this.
