### ISSUE TITLE
to_string equivalent, or `string.from_dyn`

### ISSUE THREAD

**Issue by ranfdev** [tweag/nickel#719]
**Is your feature request related to a problem? Please describe.**
I need to write a function `to_xml: record -> Str = fun s => m%"..."%m`. I need to translate record fields to strings, but the included functions in the `string` module, are pretty cumbersome to use: they are type-specific and there isn't a general `to_string` function.
   

**Describe the solution you'd like**
A function `string.from_dyn` which checks the type for me and converts any simple builtin type (num, enum, string) to a string.

**Describe alternatives you've considered**
Using ```builtin.serialize `Json v``` but that wraps string values in quotes `"`.

**Additional context**
```nickel
# for each field
m%"<attribute name="%{array.elem_at 0 field}" value="%{array.elem_at 1 field}" "%m
```

**Comment by yannham** [comment]
> Ah, string.from_enum also works on numbers, so it solves my problem. It's unexpected though. Maybe the related doc could be improved?

Hum, that's not intended. You may use it for now if that solves you problem in the waiting for a to_string function, but beware that this behavior may change in the future.

Otherwise, a to_string function with an appropriate contract is something worth considering indeed. I wonder if it should be `builtin.to_string` or `string.from_any` or `string.from_dyn`. Although the last two are a bit deceiving, because I think we will exclude records and arrays, at least at first.
