### ISSUE TITLE
Parse errors in imports are not reported

### ISSUE THREAD

**Issue by fuzzypixelz** [tweag/nickel#799]
**Describe the bug**
If a user imports a module that has a parse error, Nickel responds with `this expression has type <unevaluated>, but Type was expected`, rather than reporting the parse error.

**To Reproduce**

Create two Nickel files, `main.ncl` and `lib.ncl`:

```nickel
# main.ncl
let x = import "lib.ncl" in "Hello, " ++ x.name ++ "!"
```

```nickel
# lib.ncl
{
  name = "Nickel",,
}
```

**Expected behavior**

I would expect Nickel to report the parse error:

```console
error: unexpected token
  ┌─ lib.ncl:2:19
  │
2 │   name = "Nickel",,
  │                   ^
```

And indeed, this is exactly what we get when running `lib.ncl` directly. The issue is that running `main.ncl` yields:

```console
error: type error
  ┌─ main.ncl:1:40
  │
1 │ let x = import "lib.ncl" in "Hello, " ++ x.name ++ "!"
  │                                        ^ this expression has type <unevaluated>, but Record was expected
  │
  ┌─ lib.ncl:1:1
  │
1 │ ╭ {
2 │ │   name = "Nickel",,
3 │ │ }
  │ ╰─' evaluated to this
  │
  = field access

```

I presume that after import resolution, `x == Term::ParseError`. This could explain why a type error is raised when the evaluator tries to coerce it into a record.

**Environment**
 - OS name + version: openSUSE Tumbleweed x86_64
 - Version of the code: 0e6cc76f562c8423c4b629c4e188be8eaa82f53c

**Additional context**

Perhaps we could enrich the `Term::ParseError` variant to include the parse error itself, and take extra care to check for this special case before coercing.

But I have a question, why does `Term::ParseError` exist at all? Isn't it easier to error out when resolving the import?

**Comment by yannham** [comment]
`Term::ParseError` is here for the LSP, which needs to be error-tolerant (otherwise, a simple syntax error would preclude any basic functionality in the rest of the source file). We had a sequence of such bugs since error-tolerant parsing has been introduced, this one is just one new incarnation. Probably the parse function used when resolving import is error-tolerant, while it should be error-tolerant iff the original call was mode to the error-tolerant parsing function.
