### ISSUE TITLE
Missing field error message blames the wrong field

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#900]
**Describe the bug**
This error message doesn't make any sense:
```
nickel> { foo | Bool, bar = if foo then 2 else null }
error: missing definition for `bar`
  ┌─ repl-input-0:1:1
  │
1 │ { foo | Bool, bar = if foo then 2 else null }
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ in this record

note:
  ┌─ repl-input-0:1:9
  │
1 │ { foo | Bool, bar = if foo then 2 else null }
  │         ^^^^ bound here
```
The error presumably should say "missing definition for `foo`".

**Environment**
 - OS name + version: NixOS unstable
 - Version of the code: 741552b065108a1564eaffcf4c28a7a96bb8c047

**Comment by vkleen** [comment]
This might be related to #891, but it felt different enough to make a new issue.

**Comment by yannham** [comment]
Yes, it's different, indeed. This one is due to the heuristics we use for finding missing field information. At the point were we are trying to open a value with metadata, and find out that the metadata doesn't have any value in it, we may be deep in the evaluation of something, and we don't have the context (which record access or deep_seq operation we were doing, which record does the field come from, etc.).

So we store those kind of information on a separate call stack, and then tries to extract relevant information from said call stack. It turns out the heuristics for finding which field we were evaluating is not great...
