### ISSUE TITLE
Recursive overriding is nonassociative

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#908]
Recursive record overriding is currently nonassociative:
```
let correct_ =
{
    foo = "Overridden",
} & {
  config | {
    output | {
        value | Str,
    }
  },
} & {
  foo | Str
    | default = "blub",

  config.output.value = foo,
} in
let wrong_ =
{
    foo = "Overridden",
} & ({
  config | {
    output | {
        value | Str,
    }
  },
} & {
  foo | Str
    | default = "blub",

  config.output.value = foo,
}) in
{
  correct = correct_,
  wrong = wrong_,
}
```
yields
```
{
  wrong = { foo = "Overridden", config = { output = { value = "blub" } } },
  correct = { foo = "Overridden", config = { output = { value = "Overridden" } } } 
}
```

The semantics of record overriding should always be associative.

**Environment**
 - OS name + version: NixOS unstable
 - Version of the code: c13c51f51b61ce7617cee7796dc4113c3a1567af

**Comment by yannham** [comment]
After some quick investigations, this doesn't look like a consequence of the issues described in RFC005, but rather a plain old bug in the implementation of overriding. It seems that when a field recursively depending on another one is merged with something, the newly allocated thunks is not revertible, nor does it remember the dependencies. Which some set its value at the time, instead of staying overridable.
