### ISSUE TITLE
Would it be better to error when attempting to compare functions for equality?

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#921]
Currently, Nickel always returns `false` when comparing functions with `==`.

E.g.
```nil
let f = fun x => x in 
f == f # false
```

Given this, it seems unlikely that this behaviour is _ever_ really what a user wants and accepting this program as valid could lead to unnecessary confusion.

It might make more sense to return an error. Something like:

```
error:
   ┌─ path/to/file.ncl:2:1
   │
 2 │ f == f
   │ ^^^^^^  functions cannot be compared for equality
   │
```

**Comment by yannham** [comment]
Yes, polymorphic equality is a bit of a problem, which doesn't have a great solution without ad-hoc polymorphism, i.e. something like type classes or trait. Because the true type of equality is `forall a. Eq a => a -> a`.

We could attach an `Eq` contract to it, but that would make equality really painful to use in a statically typed environment. I agree that failing for function comparison is a reasonable thing to do.

**Comment by matthew-healy** [comment]
Great, I'll find some time to do this later this week!
