### ISSUE TITLE
 The Syntax Bikeshedding Dojo, round 9: optional & merge priorities

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#922]
# Optionals and merge priorities

Pull request #815, #827 and #845 introduced a bunch of new keyword for metadata annotations. On the verge of releasing 0.3, let's do...bikeshedding!

## Optionals 

Introduced in #815, they mark a field that is allowed to be empty without failing the evaluation or the serialization:

```nickel
let Schema = {
  foo | Str,
  bar | Num | optional,
}
```

### Current syntax

`| optional`

### Alternatives

Whatever you think of. Suggestions:

- `| opt`
- `| option` (but I find this confusing in the case of configuration, where we tend to call any field an option as well)
- `| ?` (less explicit)

## Merge priorities

#827 introduced more priorities (beside the normal one and the `default` one), including a new top priority and numeral priorities.

```nickel
{
  foo | default = 1,
  bar | force = 2,
  baz | priority 15 = 2,
}
```

### Current syntax

- `| default`: the bottom priority (smallest)
- `| force`: the top priority (highest)
- `| priority n` (`n` is a number): numeral priority, in between bottom and top, naturally ordered.

### Alternatives

Whatever you think of. Suggestions:

- `override` for `force`
- `prio` for `priority`

## Push priorities

Introduced in #845. Push a `default` or a `top` priority down a record until the leaf (a value that is not a record anymore). Initially named recursive priorities, I've found that push priorities is a bit more illustrative, and doesn't collide with all the use of `rec` that we already have (recursive bindings, records, etc.). Also named leafy priorities in the original issue.

```nickel
{
  foo  = 1,
  bar.bar  = 2,
  bar.baz = "a",
} | _push_default

# evaluates to:
#{
#  foo | default  = 1,
#  bar = {
#    bar | default  = 2,
#    bar | default = "a",
#   },
#} | _push_default
```

### Current syntax

The current syntax is temporary, and ugly on purpose:

- `| _push_default`
- `| _push_force`

### Alternatives

Whatever you think of. Suggestions:

- `| push default`/`| push force`
- `| rec default`/`| rec force`

**Comment by vkleen** [comment]
## Optionals
I like the current `| optional`.
## Merge priorities
I like the current `| default`, `| force` and `| priority n`, with `n` a floating point, as with all numbers in Nickel I think; most importantly for me would be that for any two priorities (except `default` and `force`) there is another priority in between.
## Push priorities
I vote for `| rec default` and `| rec force`, fewer new keywords that might need quoting. Also, for consistency, why not have `| rec priority n`?

**Comment by aspiwack** [comment]
`optional` is good, so are `default`, `force` and `priority n`.

I said to you in a call, I think `_push_default` should be just `default`. And the stricter default should be named something else `strict default` maybe? I guess the same should be the case for `force`? I'm not sure, I've got less clarity on the impact.

Another point, and I don't know what the situation here is, is that we probably want the default priority (that is, if I don't write a priority myself) to be `default` (the leafy one), see #240 .

**Comment by sir4ur0n** [comment]
# Optionals
`optional` looks good to me.

# Merge priorities
* I like `default`
* I dislike `force`: I don't think `force` correctly carries the meaning "opposite of default". So far I haven't found a better suggestion that clearly indicates its opposition to `default`.

If we want to make more explicit those 2, an alternative would be `bottom_priority`/`min_priority`/`minimum_priority` and `top_priority`/`max_priority`/`maximum_priority`.
I actually like this idea because now all priority keywords contain the word `priority`, so it's clearer for users that they refer to the same concept. With `default`, `force` and `priority` it's really not obvious. Even after reading the manual I wasn't quite sure they were all related to the same feature of priority.

# Push priorities
I prefer @vkleen 's suggestion of reusing `rec` over the existing (intentionally ugly) names.

I find `push` inadequate: it usually refers to pushing something of the same "type" (in a loose sense) to a collection of things of a given "type", e.g. `Array.push`.
But here, we are more... "fanning out" a priority annotation to all leaves.

Hence my alternative: `fanout`
```
{
  foo  = 1,
  bar.bar  = 2,
  bar.baz = "a",
} | fanout default # or fanout min_priority :P
```

**Comment by matthew-healy** [comment]
### Optionals

Since Nickel's syntax is JSON-inspired, how about taking some inspiration from Typescript and using `foo?` to define optional values?

This would probably go hand-in-hand with restricting optionals to only occur within bindings (so that, e.g., `x = 1 | optional` is no longer valid), which feels intuitive to me. I appreciate that isn't strictly a syntax concern, but this feels like as good a time as any to raise it.

### Merge priorities

My main issue with the current syntax is really just the keyword `force` - I don't think it's clear enough what it does from the name. What about `override` instead? This essentially mirrors `default`, and makes it clear that if you annotate a value with `override`, it will override any other possible value in merges.

### Push priorities

I think my ideal scenario would be:

- most "special" (i.e. non-contract/type) annotations are restricted to bindings
- which means we could infer `{ a = 1, b = 2 } | default` to mean "the bindings in this record are all default" rather than "this whole record has default merge prio"

This removes the need for any new keywords, while also preventing users from applying annotations that don't quite work as they might expect. Though I appreciate this might not be a change we want to consider at this time.

**Comment by yannham** [comment]
> I said to you in a call, I think _push_default should be just default. And the stricter default should be named something else strict default maybe? I guess the same should be the case for force? I'm not sure, I've got less clarity on the impact.

We discussed that internally, and with the Nix team. The conclusion is indeed that pushing default to the leaves is pretty much always what you want. However, it seems to be the converse for `force`: when you force a value, even if a record, you want it to take precedence as a block. We are faced with two choices:

- set the most used/expected for both, but at the price of consistency, with a risk of confusion. That would correspond to set `default` to means `push default` and rename the current default to `block default` for example, while keeping the current state of affairs for `force`/`push_force`.
- rather value consistency of `default/force`, and chose to switch both to be push by default, or to keep the current choice.

@sir4ur0n  has a point with respect to consistency of `default`/`force` versus priority, but in the end we found that `priority min` is way less meaningful for a devops totally external to Nickel, as opposed to `default`. It also appeared to be a documentation problem, at least in part, which can be solved.

Other than that, the two keywords seemed rather uncontroversial: override is similar but longer and without clear advantages (could also imply that you need the value to exist before you can override, which is not the case).

Optional is uncontroversial.

> Since Nickel's syntax is JSON-inspired, how about taking some inspiration from Typescript and using foo? to define optional values?

This is a legit possibility, but would be rather inconsistent with the rest of metadata. All the others (including possible future ones like `hidden`, `serialize with`, `merge`, etc.) would use proper words, but `default` would use an operator. 

It seems `rec` is more popular than `push`, so be it.

## Conclusion

- **Decided**: keep `optional`, `force` and `default` as keywords.
- **Need action**: should we have recursive priorities be the meaning of `force`/`default`, stay as we are, or have a mix (`default` would be recursive and `force` wouldn't)
- **Decided**: use `rec force`/`rec default` if we need to have separate keywords for recursive priorities.
- **Decided**: use `block force`/`block default` if we set recursive priorities to be the standard ones, and we need. No great solutions here but `block` seemed to be the least disliked.

**Comment by yannham** [comment]
Note that, until 1.0, nothing is set in stone either, although we should avoid to change the syntax as much as possible. @sir4ur0n proposed to use AB testing on people actually representing the potential user-base of Nickel, or at least a more data-based approach. I think that could be indeed useful before the 1.0 milestone.

**Comment by matthew-healy** [comment]
Happy with all of these decisions, though I have to say I _really_ dislike `block force`/`block default`. I don't think the meaning is clear at all. 

As such, my vote would be to keep `force` and `default` as value priorities and require `rec force` and `rec default` to push them down into records.

**Comment by matthew-healy** [comment]
One alternative idea would be to have the _position_ of the annotation impact the meaning. For example:

```
{
  x = { 
    a = 1,
    b = 2,
  } | default
}
```
could result in `a | default`, `b | default`, whereas:
```
{ 
  x | default = {
    a = 1,
    b = 2,
  }
}
```
would result in `x | default`.

**Comment by Radvendii** [comment]
RE `_push_default` etc. I appologize for the rambly nature of these comments. I don't have a very clear picture in my head of what this should look like.

---

we could have `push default` **and** `block default`, and disallow using a raw `default` annotation on records. (same for `force`). The error message could then suggest the one most frequently used in that situation.

---

How do we deal with this case?
```
{
  foo  = 1,
  bar.bar | force = 2,
  bar.baz = "a",
} | _push_default
```

And this one? My intuition is the expected behaviour is opposite here than with a record literal.

```
let baz = { bar = 2, baz = 3 }; in // not sure what the syntax for this is in nickel exactly
{
  foo  = 1,
  bar = baz,
} | default
```

---

While I agree that most of the time I want *some* kind of pushing down of default values, how far I want them to push down varries. Sometimes a record is used to encode a "single value" (morally), and I wouldn't want the priority to be pushed down through that. The most obvious example is NixOS configurations themselves. They are represented as attrsets with additional attributes like `__type` or something, and if the default annotation got pushed down all the way to the non-record values, you'd have all sorts of problems.

Nickel may not run into this problem as much, because we're trying to replace the NixOS module system with built-in types and annotations, but I expect something else will arise in the future that uses Nickel records to encode some other information.

One solution to this is wrapping those records in some kind of opaque newtype that blocks pushing from going through them? I'm not sure what already exists in this regard.

---

What if we have push-down semantics by default, and then have an additional annotation `| newtype` (name pending bikeshed. could be `| block` or whatever), which prevents pushing through it. That way to get the other semantics you do `| newtype | default`, but we could also have more granularity.
