### ISSUE TITLE
Add a record mapping function that preserves recursive dependencies

### ISSUE THREAD

**Issue by vkleen** [tweag/nickel#976]
WHile prototyping approaches for Terraform+Nickel and Nix+Nickel, we were trying to map over recursively defined records while still allowing overrides to take place after the mapping operation. Currently, the record map primop returns a new record devoid of the dependency information required for recursive overriding. Analysis by @yannham:
> For more context around the initial discussion, as long as something is stored in a revertible thunk, it is well, revertible, even if it has been forced/evaluated before. You lose this ability when you allocate standard thunks for the record fields, which only remember one value, but not the original expression nor the dependencies. The culprit here is that record.map probably just allocates standard thunk to populate the fields of the new allocated record. If instead we map over the original thunks using Thunk::map, then we would get the behavior we want.

I see three possible approaches for addressing this:
- Add a second kind of record mapping primop (probably with an ugly name to be bikeshed later) that preserves revertible thunks and similarly for other primops where it makes sense.
- Make `record.map` and all other similar primops preserve revertibility for thunks and add a `resolve` primop (name of course to be bikeshed) for finalizing a record, convertink all revertible thunks into standard ones.
- Do nothing and try to deal with the current semantics. E.g. don't map over a record if you want fields to stay overridable.

For context, the Nickel code
```
({
  foo = 1,
  reference = foo,
} |> record.map (fun name field => field)) & {
  foo | force = 2
}
```
exports to the JSON
```
{
  "foo": 2,
  "ref": 1
}
```
which seems unintuitive to me.

**Comment by yannham** [comment]
This issue was discussed during the team meeting. In the end we seemed to agree that `record.map` should probably act on recursive records (thus preserving resistivity) rather than "freezing" the recursive record to a normal record. We would provide a new special builtin to freeze a recursive record, instead of a second map operation. Indeed:

- There is at least one concrete use-case for a recursive `record.map`, documented in this issue.
- This feels natural, because `record.map` is a fundamental operation on records, and can be expressed quite naturally on recursive records. One conceptual approach is to think of recursive records being a representation of a function of a `self` record returning a record: `repr_as_fun ~ fun self => {field1 = exp1, .., fieldn = expn}`. Then, `record.map f` would just push `f` inside the record while preserving the function: `repr_as_fun_mapped ~ fun self => {field1 = f exp1, .., fieldn = f expn}`, or put differently, `expr_as_fun_mapped ~ record.non_recursive_map f ¤ repr_as_fun` where `¤` is function composition. So it's really function (post)composition.
- We couldn't come up with an obvious use-case where you would want a non-recursive map. "Freezing" (computing the fixpoint, resolving) a recursive record doesn't seem like an operation you want to do often. We may provide a builtin to do so anyway, but we expect that it's rare, "expert" use-case, while wanting a recursivity-preserving `record.map` would be more common.

**Comment by vkleen** [comment]
I've found another instance where this manifests itself. Applying a dictionary contract `{_: T}` is implemented as mapping an `%assume% T` primop over the record it is applied to. With the current record mapping semantics this has the effect of destroying all recursive thunks, so we end up with the following behaviour:
```
nickel> ({ a = 1, b = a } | { _: Num }) & { a | force = 2 }
{ a = 2, b = 1 }
```
while of course
```
nickel> { a = 1, b = a } & { a | force = 2 }
{ a = 2, b = 2 }
```
In effect a record becomes non-overridable as soon as a dictionary contract is applied. I conjecture that that's also the root cause of #892.

**Comment by vkleen** [comment]
It turns out this issue is more complicated than previously thought. First, let me describe the semantics I originally envisioned for this lazy record mapping. A recursive record `{foo = 1, bar = foo + 1}` in Nickel can be thought of as a function `fun self => { foo = 1, bar = self.foo + 1 }`. Evaluation of the record then forms a fixed point.

Given this situation, a lazy `record.map f` would produce
```nickel
fun self => {
  foo = f "foo" 1,
  bar = f "bar" (self.foo + 1),
}
```
This operation can't be given a reasonable type. Just consider what should happen for `f` being `fun key value => string.from value`. Then the recursive access to `foo` in the definition of `bar` would try to increment a string after the mapping operation, transforming a well-typed record into an ill-typed one. Consequently, we decided to abandon the idea of a fully lazy, general `record.map`.

However, we have already implemented a special case of a fully lazy record mapping operation in #1141. This operation makes sense for contracts. For instance, in the example above, the fact that `foo` evaluated to a number would be an error if a dictionary contract `{_: String}` were applied to the record. And if `bar` relied on `foo` being a number, the contract failing would be entirely expected.
